# Generated by Django 2.2.1 on 2019-07-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_ba', '0002_auto_20190728_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Board',
        ),
    ]
