# Generated by Django 2.2.1 on 2019-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_ba', '0003_auto_20190728_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('content', models.TextField(blank=True, null=True)),
                ('lookup', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
