# Generated by Django 2.2.1 on 2019-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(choices=[('페트병 플라스틱류', '페트병 플라스틱류'), ('기타 플라스틱류', '기타 플라스틱류'), ('일반', '일반쓰레기'), ('음식물', '음식물쓰레기'), ('유리', '유리'), ('병', '병'), ('대형', '대형폐기물'), ('종이류', '종이류'), ('종이팩류', '종이팩류'), ('종이팩', '종이팩'), ('금속캔', '금속캔'), ('유리병류', '유리병류'), ('고철류', '고철류'), ('비닐류', '비닐류'), ('스티로폼 완충재', '스틔로폼 완충제'), ('의류', '의류'), ('폐형광등', '폐형광등'), ('폐건전지', '폐건전지'), ('폐가전제품', '폐가전제품'), ('대형폐기물', '대형폐기물'), ('소형가전제품', '소형가전제품')], max_length=20),
        ),
    ]
